### ISSUE TITLE
Confused or bug... `App Extension (qenv): missing QENV environment variable; skipping`

### ISSUE THREAD

**Issue by corepay** [quasarframework/app-extension-qenv#6] opened 2019-07-21 17:06 UTC
### Fresh Quasar build from CLI

First order of business was installing your extension:  

![image](https://user-images.githubusercontent.com/48992923/61594185-a9a3e980-abb6-11e9-9ad9-5cbcc8adecb3.png)

### Next was updating start scripts in package.json

![image](https://user-images.githubusercontent.com/48992923/61594209-fedffb00-abb6-11e9-863b-def8ae9ded95.png)

### Restarting Server...

`App Extension (qenv): missing QENV environment variable; skipping`

![image](https://user-images.githubusercontent.com/48992923/61594226-5d0cde00-abb7-11e9-9837-026eaed70516.png)

### TESTED:

I put a computed property for `process.env.ENV_TYPE` in my freshly created Index.vue.

![image](https://user-images.githubusercontent.com/48992923/61594263-cd1b6400-abb7-11e9-8691-066f234df6ba.png)

No property shown or indicator anything is wrong.

![image](https://user-images.githubusercontent.com/48992923/61594287-17044a00-abb8-11e9-9c8a-08ba8d9a7467.png)

Apologize beforehand if this is oversight - went through readme several times and have some practical quasar experience behind me with a few apps under my belt.....

![image](https://user-images.githubusercontent.com/48992923/61594318-8aa65700-abb8-11e9-9e03-465c9bc66b53.png)

**Comment by lucasfernog** [comment] 2019-07-21 17:08
Did you start the server by running 'yarn dev'?

**Comment by corepay** [comment] 2019-07-21 17:09
Yes sir

**Comment by lucasfernog** [comment] 2019-07-21 17:13
Are you running on Windows?

**Comment by corepay** [comment] 2019-07-21 17:16
THAT WAS IT!

![image](https://user-images.githubusercontent.com/48992923/61594347-f4266580-abb8-11e9-986a-733ad1099b6a.png)


So - I would recommend this a little more clear in the docs.  I see now of course I am calling `quasar dev` in my start script but it really is not that obvious unless you are super in tune and experienced with the quasar framework and the CLI.  Just a note about now use `yarn dev` instead of the `quasar dev` after installing this plugin and putting `quasar dev` in the start script can probably save us and you some future time.

**Comment by corepay** [comment] 2019-07-21 17:17
Not on Windows (your cross-env instructions are pretty clear there AND also is where the docs refer the user to use `yarn dev`.  I skipped that all together cuz not on Windows

**Comment by hawkeye64** [comment] 2019-07-21 21:45
@corepay It's on my list to update the readme. It was one of my fiirst App Extensions. I'm much better at it now. So, revisiting them should clarify some steps needed. For now, will close this.
:heart: Thanks for letting us know the docs could be better.

**Closed as completed by hawkeye64** 2019-07-21 21:45 UTC

**Comment by corepay** [comment] 2019-07-21 22:59
@hawkeye64 no problem, I appreciate your work and making it ready for me and my projects.  

Thank you.

**Comment by morgler** [comment] 2020-11-04 07:41
I have the same problem and I think I do call it correctly. Still I cannot see any of the env vars in my Quasar app:

```
> yarn serve
$ QENV=development quasar dev
```

In my component I call `console.log('env', process.env.ENV_TYPE)`, which always gives `undefined`. Other env vars like Quasar's `process.env.MODE` do work flawlessly.

Am I missing something or is this a bug?

**Comment by hawkeye64** [comment] 2020-11-05 13:43
@morgler Running windows? With `$` I am assuming linux
Let's see you structured your `.quasar.env.json` file

**Comment by morgler** [comment] 2020-11-06 06:51
Linux indeed (MacOS). The `.quasar.env.json` is just the one generated by qenv initially:

```
{
  "development": {
    "ENV_TYPE": "Running Development",
    "ENV_DEV": "Development",
  },
  "production": {
    "ENV_TYPE": "Running Production",
    "ENV_PROD": "Production",
  },
  "test": {
    "ENV_TYPE": "Running Test",
    "ENV_Test": "Test",
  }
}
```

I could since get it to work with dotenv, but had no luck with qenv. I simply don't know why the env vars are not passed on to `process.env`.

**Comment by bonatoc** [comment] 2020-12-05 01:01
On MacOS X, depending on you installed quasar and/or yarn, sometimes it's just a question of prefixing with `sudo`.

```
  "scripts": {
    "lint": "eslint --ext .js,.vue ./",
    "test": "echo \"No test specified\" && exit 0",
    "dev": "sudo QENV=dev quasar dev",
    "staging": "sudo QENV=staging quasar dev",
    "deploy-to-staging": "firebase use default && sudo QENV=staging quasar build -m pwa && firebase deploy",
    "deploy-to-production": "firebase use production && sudo QENV=production quasar build -m pwa && firebase deploy"
  },
```

**Comment by lupodellasleppa** [comment] 2021-03-18 09:56
Kinda late on this one but for anyone who stumbles upon this, just check the `.quasar.env.json` is a valid JSON file. In my case I had some trailing commas breaking the JSON and that would be the cause of QENV not loading

**Comment by hawkeye64** [comment] 2021-03-19 13:34
I like to use this web site to validate JSON: https://jsonformatter.curiousconcept.com/
